
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{

using System;
    using System.Collections.Generic;
    
public partial class ComentarioObjetivo
{

    public int ComentarioId { get; set; }

    public int FormularioId { get; set; }

    public string Comentarioobj1 { get; set; }

    public string Comentarioobj2 { get; set; }

    public string Comentarioobj3 { get; set; }

    public string Comentarioobj4 { get; set; }

}

}
