
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{

using System;
    using System.Collections.Generic;
    
public partial class DescripcionP
{

    public int DescripcionId { get; set; }

    public Nullable<int> FormularioId { get; set; }

    public Nullable<int> UsuarioId { get; set; }

    public string Dp18 { get; set; }

    public string Dp19 { get; set; }

    public string Dp20 { get; set; }

    public string Dp27 { get; set; }

    public string Dp28 { get; set; }

    public string Dp29 { get; set; }

    public string Dp30 { get; set; }

    public string Dp31 { get; set; }

    public string Dp32 { get; set; }

}

}
