

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DominicanalimpiaEntities2 : DbContext
{
    public DominicanalimpiaEntities2()
        : base("name=DominicanalimpiaEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Formulario> Formulario { get; set; }

    public virtual DbSet<Preguntas> Preguntas { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    public virtual DbSet<Municipios> Municipios { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Escuelas> Escuelas { get; set; }

    public virtual DbSet<FormularioM> FormularioM { get; set; }

    public virtual DbSet<Objetivo1> Objetivo1 { get; set; }

    public virtual DbSet<DescripcionP> DescripcionP { get; set; }

}

}

