

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DominicanalimpiaEntities2 : DbContext
{
    public DominicanalimpiaEntities2()
        : base("name=DominicanalimpiaEntities2")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Formulario> Formulario { get; set; }

    public virtual DbSet<Preguntas> Preguntas { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    public virtual DbSet<Municipios> Municipios { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

}

}

