
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{
    using DominicanaLimpia.ModelViews;
    using System;
    using System.Collections.Generic;
    
public partial class Formulario : FormularioModelView
{

    public int FormularioId { get; set; }

    public Nullable<int> PreguntaId { get; set; }

    public Nullable<int> Valor { get; set; }

    public Nullable<System.DateTime> Desde { get; set; }

    public Nullable<System.DateTime> Hasta { get; set; }

    public string Comentario { get; set; }

    public Nullable<int> Idusuario { get; set; }

    public string Estatus { get; set; }

    public Nullable<int> ProvinciaId { get; set; }

    public Nullable<int> NumeroFormulario { get; set; }

}

}
