
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{
    using DominicanaLimpia.ModelViews;
    using System;
    using System.Collections.Generic;
    
public partial class FormularioM : FormularioModelView
    {

    public int FormularioId { get; set; }

    public Nullable<System.DateTime> Desde { get; set; }

    public Nullable<System.DateTime> Hasta { get; set; }

    public Nullable<int> UsuarioId { get; set; }

    public Nullable<int> ProvinciaId { get; set; }

    public Nullable<int> NumeroFormulario { get; set; }

    public string Estatus { get; set; }

    public string Comentario { get; set; }

    public Nullable<int> P13 { get; set; }

    public Nullable<int> P14 { get; set; }

    public Nullable<int> P15 { get; set; }

    public Nullable<int> P16 { get; set; }

    public Nullable<int> P17 { get; set; }

    public Nullable<int> P18 { get; set; }

    public Nullable<int> P19 { get; set; }

    public Nullable<int> P20 { get; set; }

    public Nullable<int> P21 { get; set; }

    public Nullable<int> P22 { get; set; }

    public Nullable<int> P23 { get; set; }

    public Nullable<int> P24 { get; set; }

    public Nullable<int> P25 { get; set; }

    public Nullable<int> P26 { get; set; }

    public Nullable<int> P27 { get; set; }

    public Nullable<int> P28 { get; set; }

    public Nullable<int> P29 { get; set; }

    public Nullable<int> P30 { get; set; }

    public Nullable<int> P31 { get; set; }

    public Nullable<int> P32 { get; set; }

}

}
