
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{
    using DominicanaLimpia.ModelViews;
    using System;
    using System.Collections.Generic;
    
public partial class Formulario : FormularioModelView
    {

    public int FormularioId { get; set; }

    public Nullable<int> PreguntaId { get; set; }

    public Nullable<int> Valor { get; set; }

    public Nullable<System.DateTime> Desde { get; set; }

    public Nullable<System.DateTime> Hasta { get; set; }

    public string Comentario { get; set; }

    public Nullable<int> Idusuario { get; set; }

    public string Estatus { get; set; }

    public Nullable<int> ProvinciaId { get; set; }

    public Nullable<int> NumeroFormulario { get; set; }

}

}
