
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{

using System;
    using System.Collections.Generic;
    
public partial class FormularioM
{

    public int FormularioId { get; set; }

    public Nullable<System.DateTime> Desde { get; set; }

    public Nullable<System.DateTime> Hasta { get; set; }

    public Nullable<int> UsuarioId { get; set; }

    public Nullable<int> ProvinciaId { get; set; }

    public Nullable<int> NumeroFormulario { get; set; }

    public string Estatus { get; set; }

    public string Comentario { get; set; }

    public Nullable<int> P13 { get; set; }

    public Nullable<int> P14 { get; set; }

    public Nullable<int> P15 { get; set; }

    public Nullable<int> P16 { get; set; }

    public Nullable<int> P17 { get; set; }

    public Nullable<int> P18 { get; set; }

    public Nullable<int> P19 { get; set; }

    public Nullable<int> P20 { get; set; }

    public Nullable<int> P21 { get; set; }

    public Nullable<int> P22 { get; set; }

    public Nullable<int> P23 { get; set; }

    public Nullable<int> P24 { get; set; }

    public Nullable<int> P25 { get; set; }

    public Nullable<int> P26 { get; set; }

    public Nullable<int> P27 { get; set; }

    public Nullable<int> P28 { get; set; }

    public Nullable<int> P29 { get; set; }

    public Nullable<int> P30 { get; set; }

    public Nullable<int> P31 { get; set; }

    public Nullable<int> P32 { get; set; }

}

}
