
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{

using System;
    using System.Collections.Generic;
    
public partial class Objetivo1
{

    public int ObjetivoId { get; set; }

    public Nullable<int> FormularioId { get; set; }

    public Nullable<int> EscuelaId { get; set; }

    public Nullable<int> UsuarioId { get; set; }

    public Nullable<int> p1 { get; set; }

    public Nullable<int> p2 { get; set; }

    public Nullable<int> p3 { get; set; }

    public Nullable<int> p4 { get; set; }

    public Nullable<int> p5 { get; set; }

    public Nullable<int> p6 { get; set; }

    public Nullable<int> p7 { get; set; }

    public Nullable<int> p8 { get; set; }

    public Nullable<int> p9 { get; set; }

    public Nullable<int> p10 { get; set; }

    public Nullable<int> p11 { get; set; }

    public Nullable<int> p12 { get; set; }

    public Nullable<int> MunicipioId { get; set; }

    public Nullable<System.DateTime> Desde { get; set; }

    public Nullable<System.DateTime> Hasta { get; set; }

    public Nullable<int> P111 { get; set; }

    public Nullable<int> P112 { get; set; }

}

}
