
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DominicanaLimpia
{
    using DominicanaLimpia.ModelViews;
    using System;
    using System.Collections.Generic;
    
public partial class Usuarios : UsuariosModelView
    {

    public int UsuarioId { get; set; }

    public string Usuario { get; set; }

    public string Clave { get; set; }

    public string Nombre_Completo { get; set; }

    public string Correo { get; set; }

    public Nullable<int> RolId { get; set; }

    public string Estatus { get; set; }

    public Nullable<int> MunicipioId { get; set; }

    public string MunicipiosId { get; set; }

    public Nullable<int> ResponsableId { get; set; }

}

}
